import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export async function verifyInputs(root) {
  const registry = JSON.parse(await readFile(join(root, '.packaging/models/registry.json'), 'utf8'));
  const manifest = JSON.parse(await readFile(join(root, 'backend/models.json'), 'utf8'));
  const preset = manifest.presets[0];
  const entry = registry[`${preset.adapter}:${preset.repo_id}@${preset.revision}`];
  if (!entry || entry.resolved_revision !== preset.revision) throw new Error('The pinned default Laya checkpoint must be bundled before packaging.');
  const modelRoot = resolve(root, '.packaging/models');
  const modelPath = resolve(modelRoot, entry.path);
  if (!modelPath.startsWith(`${join(modelRoot, 'cache')}/`) && !modelPath.startsWith(`${join(modelRoot, 'cache')}\\`)) throw new Error('Model path escapes the release cache.');
  for (const name of ['model.safetensors', 'rl_agent_config.json']) {
    if (!(await stat(join(modelPath, name))).isFile()) throw new Error(`Missing model artifact: ${name}`);
  }
  for (const name of ['dist/index.html', '.packaging/python-licenses.json', '.packaging/python-versions.txt', '.packaging/models/LICENSE-LAYA.txt']) await stat(join(root, name));
  const runner = join(root, '.packaging/runtime/invoice-runner', process.platform === 'win32' ? 'invoice-runner.exe' : 'invoice-runner');
  if (!(await stat(runner)).isFile()) throw new Error('Build the native Python runner with PyInstaller first.');
}

export async function stageDesktop(root) {
  await verifyInputs(root);
  const output = join(root, '.packaging/resources');
  // This directory is exclusively generated by this script; never clear source/model caches.
  await rm(output, { recursive: true, force: true });
  await mkdir(join(output, 'licenses'), { recursive: true });
  await cp(join(root, 'dist'), join(output, 'ui'), { recursive: true });
  await cp(join(root, '.packaging/runtime/invoice-runner'), join(output, 'runner'), { recursive: true });
  await cp(join(root, '.packaging/models'), join(output, 'models'), { recursive: true, dereference: true });
  await cp(join(root, '.packaging/python-licenses.json'), join(output, 'licenses/python-licenses.json'));
  await cp(join(root, '.packaging/python-versions.txt'), join(output, 'licenses/python-versions.txt'));
  const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
  const frontendVersions = {};
  const pending = [...Object.keys(pkg.dependencies), 'scheduler'];
  for (const name of pending) {
    if (frontendVersions[name]) continue;
    const dependencyRoot = join(root, 'node_modules', name);
    const dependency = JSON.parse(await readFile(join(dependencyRoot, 'package.json'), 'utf8'));
    frontendVersions[name] = dependency.version;
    const licenseDir = join(output, 'licenses', 'frontend', name.replace(/[^a-z0-9.-]/gi, '_'));
    await mkdir(licenseDir, { recursive: true });
    const licenses = (await readdir(dependencyRoot)).filter(file => /^(license|copying|ofl)([.-]|$)/i.test(file));
    if (!licenses.length) throw new Error(`Missing frontend license for ${name}.`);
    for (const file of licenses) await cp(join(dependencyRoot, file), join(licenseDir, file), { recursive: true });
  }
  await writeFile(join(output, 'licenses/frontend-versions.json'), JSON.stringify(frontendVersions, null, 2));
  await writeFile(join(output, 'build-info.json'), JSON.stringify({ version: pkg.version, platform: process.platform, arch: process.arch, model: JSON.parse(await readFile(join(root, 'backend/models.json'), 'utf8')).presets[0] }, null, 2));
  console.log(`Desktop resources staged at ${output}`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await stageDesktop(process.cwd());
