import { Plus, Trash2, ArrowLeft, Printer, Save, RefreshCw, Eye, Check, Download } from 'lucide-react';
import { useState } from 'react';
import { Button, Field, Input, Select, Textarea, SectionTitle } from './ui';
import InvoiceDocument from './InvoiceDocument';
import { totals, formatMoney, snapshotAssets, uid, type Invoice, type Workspace } from './model';
import { invoiceInputCSV } from './csv';
import { downloadFile } from './storage';

export default function InvoiceEditor({ workspace, invoice, onChange, onSave, onPrint, onBack, isSaved, dirty }: {
  workspace: Workspace; invoice: Invoice; onChange: (invoice: Invoice) => void;
  onSave: () => void; onPrint: () => void; onBack: () => void; isSaved: boolean; dirty: boolean;
}) {
  const [mobilePreview, setMobilePreview] = useState(false);
  const amount = totals(invoice);
  const set = <K extends keyof Invoice>(key: K, value: Invoice[K]) => onChange({ ...invoice, [key]: value });
  const changeTemplate = (id: string) => {
    const template = workspace.templates.find(value => value.id === id);
    if (!template) return;
    onChange({ ...invoice, template: structuredClone(template), business: { ...workspace.business }, assets: snapshotAssets(template, workspace.assets), items: invoice.items.map(item => ({ ...item, taxRate: template.taxMode === 'none' ? 0 : item.taxRate })), customValues: {} });
  };
  const refreshBranding = () => {
    const template = workspace.templates.find(value => value.id === invoice.template.id) || invoice.template;
    if (!window.confirm('Update this invoice to your current business details and template? Existing custom field values will be kept.')) return;
    onChange({ ...invoice, template: structuredClone(template), business: { ...workspace.business }, assets: snapshotAssets(template, workspace.assets), items: invoice.items.map(item => ({ ...item, taxRate: template.taxMode === 'none' ? 0 : item.taxRate })) });
  };
  return <>
    <div className="page-heading editor-heading"><div><button className="back-link" onClick={onBack}><ArrowLeft size={15} />All invoices</button><h1>{isSaved ? 'Edit invoice' : 'Create an invoice'}<span className="quiet-tag">{dirty ? 'Unsaved changes' : 'Saved'}</span></h1><p>A few details. One beautifully made invoice.</p></div><div className="heading-actions"><Button className="mobile-preview-button" onClick={() => setMobilePreview(!mobilePreview)}><Eye size={16} />{mobilePreview ? 'Edit details' : 'Preview'}</Button><Button title="Export all current input values, including unsaved changes" onClick={() => downloadFile(`${invoice.number.replace(/[^a-z0-9_-]/gi, '_') || 'invoice'}-input.csv`, invoiceInputCSV([invoice]), 'text/csv;charset=utf-8')}><Download size={16} />Export input</Button><Button onClick={onSave}><Save size={16} />Save invoice</Button><Button variant="primary" onClick={onPrint}><Printer size={16} />Print / PDF</Button></div></div>
    <div className={`editor-grid ${mobilePreview ? 'show-preview' : ''}`}>
      <div className="editor-form">
        <section className="card form-section"><SectionTitle number="01" title="Invoice details" /><div className="form-grid"><Field label="Template"><Select value={invoice.template.id} onChange={e => changeTemplate(e.target.value)}>{!workspace.templates.some(t => t.id === invoice.template.id) && <option value={invoice.template.id}>{invoice.template.name} (archived)</option>}{workspace.templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</Select></Field><Field label="Invoice number *"><Input value={invoice.number} maxLength={100} onChange={e => set('number', e.target.value)} /></Field><Field label="Invoice date *"><Input type="date" value={invoice.issueDate} onChange={e => set('issueDate', e.target.value)} /></Field><Field label="Due date *"><Input type="date" value={invoice.dueDate} min={invoice.issueDate} onChange={e => set('dueDate', e.target.value)} /></Field></div><div className="inline-note"><span>Branding is captured with each invoice.</span><button className="text-button" onClick={refreshBranding}><RefreshCw size={12} />Use latest settings</button></div></section>
        <section className="card form-section"><SectionTitle number="02" title="Customer details" /><div className="form-grid"><Field label="Customer / company name *" className="span-2"><Input placeholder="Who is this invoice for?" value={invoice.customer.name} maxLength={200} onChange={e => set('customer', { ...invoice.customer, name: e.target.value })} /></Field><Field label="Email"><Input type="email" placeholder="customer@example.com" value={invoice.customer.email} onChange={e => set('customer', { ...invoice.customer, email: e.target.value })} /></Field><Field label="Phone"><Input type="tel" placeholder="+91" value={invoice.customer.phone} onChange={e => set('customer', { ...invoice.customer, phone: e.target.value })} /></Field><Field label="Billing address" className="span-2"><Textarea placeholder="Street address, city, state and postal code" value={invoice.customer.address} onChange={e => set('customer', { ...invoice.customer, address: e.target.value })} /></Field><Field label="Customer GSTIN / tax ID"><Input placeholder="Optional" value={invoice.customer.gstin} onChange={e => set('customer', { ...invoice.customer, gstin: e.target.value })} /></Field>{invoice.template.customFields.map(field => <Field key={field.id} label={field.label}><Input value={invoice.customValues[field.id] || ''} placeholder={field.placeholder} onChange={e => set('customValues', { ...invoice.customValues, [field.id]: e.target.value })} /></Field>)}</div></section>
        <section className="card form-section"><SectionTitle number="03" title="Items & services"><span className="count-tag">{invoice.items.length} items</span></SectionTitle><div className="line-items">{invoice.items.map((item, index) => {
          const update = (patch: Partial<typeof item>) => set('items', invoice.items.map(i => i.id === item.id ? { ...i, ...patch } : i));
          return <div className="line-item" key={item.id}><div className="line-item-heading"><span>ITEM {String(index + 1).padStart(2, '0')}</span><button className="icon-button danger-text" aria-label={`Remove item ${index + 1}`} disabled={invoice.items.length === 1} onClick={() => set('items', invoice.items.filter(i => i.id !== item.id))}><Trash2 size={15} /></button></div><Field label="Description *"><Input value={item.description} maxLength={2000} placeholder="Product or service" onChange={e => update({ description: e.target.value })} /></Field><div className="item-numbers"><Field label="Quantity *"><Input type="number" min="0.001" max="1000000" step="any" value={item.quantity} onChange={e => update({ quantity: e.target.valueAsNumber || 0 })} /></Field><Field label={`Rate (${invoice.business.currency}) *`}><Input type="number" min="0" max="1000000000" step="0.01" value={item.rate} onChange={e => update({ rate: e.target.valueAsNumber || 0 })} /></Field>{invoice.template.taxMode !== 'none' && <Field label="Tax %"><Input type="number" min="0" max="100" step="0.01" value={item.taxRate} onChange={e => update({ taxRate: e.target.valueAsNumber || 0 })} /></Field>}<Field label="Discount %"><Input type="number" min="0" max="100" step="0.01" value={item.discount} onChange={e => update({ discount: e.target.valueAsNumber || 0 })} /></Field></div><div className="item-footer">{invoice.template.showHSN ? <Field label="HSN / SAC"><Input placeholder="Optional code" value={item.hsn} onChange={e => update({ hsn: e.target.value })} /></Field> : <span />}<strong>{formatMoney(amount.lines[index].total / 100, invoice.business.currency)}</strong></div></div>;
        })}</div><Button className="add-item" onClick={() => set('items', [...invoice.items, { id: uid(), description: '', hsn: '', quantity: 1, rate: 0, taxRate: invoice.template.taxMode === 'none' ? 0 : invoice.business.defaultTax, discount: 0 }])} disabled={invoice.items.length >= 200}><Plus size={16} />Add line item</Button><div className="editor-total"><span>Invoice total <small>Including applicable tax</small></span><strong>{formatMoney(amount.total, invoice.business.currency)}</strong></div></section>
        <section className="card form-section"><SectionTitle number="04" title="Finishing touches" /><div className="form-grid"><Field label="Notes" className="span-2"><Textarea value={invoice.notes} placeholder="A personal note or additional instructions…" onChange={e => set('notes', e.target.value)} /></Field><Field label="Status"><Select value={invoice.status} onChange={e => onChange({ ...invoice, status: e.target.value as Invoice['status'], paid: e.target.value === 'paid' ? amount.total : invoice.paid })}><option value="draft">Draft</option><option value="issued">Issued</option><option value="paid">Paid</option></Select></Field><Field label={`Amount paid (${invoice.business.currency})`}><Input type="number" min="0" max={amount.total} step="0.01" value={invoice.paid} onChange={e => set('paid', e.target.valueAsNumber || 0)} /></Field></div><p className="muted small">All amounts are tax-exclusive. Discounts are applied before tax. Printing saves the invoice without changing its status.</p></section>
      </div>
      <aside className="preview-panel"><div className="preview-topbar"><span><span className="live-dot" />LIVE PREVIEW</span><span>A4 · Portrait</span></div><div className="paper-container"><InvoiceDocument invoice={invoice} /></div><div className="preview-caption"><Check size={14} /><span>Print-ready. Select “Save as PDF” in your print dialog.</span></div></aside>
    </div>
  </>;
}
