import { useEffect, useState } from 'react';
import { Plus, ArrowLeft, Copy, Trash2, Save, LayoutTemplate, SlidersHorizontal, Image, Type, Check } from 'lucide-react';
import { Button, Field, Input, Select, Textarea, Toggle, SectionTitle } from './ui';
import { defaultTemplate, newInvoice, templateSchema, uid, type Template, type Workspace } from './model';
import InvoiceDocument from './InvoiceDocument';

export default function Templates({ workspace, onSave, onDelete, onCreateInvoice, onPendingChange, notify }: {
  workspace: Workspace; onSave: (template: Template) => void; onDelete: (id: string) => void;
  onCreateInvoice: (template: Template) => void; notify: (text: string, error?: boolean) => void;
  onPendingChange: (warning: string) => void;
}) {
  const [editing, setEditing] = useState<Template | null>(null);
  const [tab, setTab] = useState<'design' | 'content'>('design');
  useEffect(() => {
    const original = workspace.templates.find(template => template.id === editing?.id);
    onPendingChange(editing && JSON.stringify(editing) !== JSON.stringify(original) ? 'Your template has unsaved changes. Leave without saving?' : '');
  }, [editing, workspace.templates, onPendingChange]);
  const set = <K extends keyof Template>(key: K, value: Template[K]) => setEditing(current => current && ({ ...current, [key]: value }));
  const sample = (template: Template) => {
    const invoice = newInvoice(workspace, template);
    invoice.customer = { name: 'Aarav Sharma', address: '24, Park Road\nBengaluru, Karnataka 560001', email: 'aarav@example.com', phone: '', gstin: '' };
    invoice.items = [{ id: 'sample-1', description: 'Consultation', hsn: '', quantity: 1, rate: 1500, taxRate: template.taxMode === 'none' ? 0 : 18, discount: 0 }, { id: 'sample-2', description: 'Materials', hsn: '', quantity: 2, rate: 450, taxRate: template.taxMode === 'none' ? 0 : 18, discount: 0 }];
    invoice.customValues = Object.fromEntries(template.customFields.map(f => [f.id, f.placeholder || 'Sample value']));
    invoice.notes = '';
    return invoice;
  };
  const save = () => {
    const result = templateSchema.safeParse(editing);
    if (!result.success) { notify(`Please check ${result.error.issues[0].path.join(' → ')}: ${result.error.issues[0].message}`, true); return; }
    onSave(result.data); setEditing(null);
  };
  if (!editing) return <>
    <div className="page-heading"><div><div className="eyebrow">MAKE IT YOURS</div><h1>Invoice templates</h1><p>Your brand, down to the last detail.</p></div><Button variant="primary" onClick={() => setEditing({ ...defaultTemplate(), name: 'Untitled template', logoAssetId: workspace.assets.find(a => a.kind === 'logo')?.id || '' })}><Plus size={17} />Create template</Button></div>
    <div className="info-strip"><LayoutTemplate size={19} /><p>Start with a layout, add your branding, and choose the details that matter. Saved invoices keep their original design.</p></div>
    <div className="template-grid">{workspace.templates.map(template => <article className="card template-card" key={template.id}><button className="template-thumbnail" aria-label={`Edit ${template.name}`} onClick={() => setEditing(structuredClone(template))}><div className="thumbnail-paper"><InvoiceDocument invoice={sample(template)} sample /></div><span className="thumbnail-edit"><SlidersHorizontal size={15} />Customize</span></button><div className="template-card-content"><div><h3>{template.name}</h3><span className="muted small">{template.layout} layout · {template.taxMode === 'split' ? 'CGST + SGST' : template.taxMode === 'single' ? 'Single tax' : 'Tax-free'}</span></div><div className="template-card-actions"><Button onClick={() => onCreateInvoice(template)}>Use template</Button><button className="icon-button" title="Duplicate template" aria-label={`Duplicate ${template.name}`} onClick={() => setEditing({ ...structuredClone(template), id: uid(), name: `${template.name.slice(0, 85)} (copy)` })}><Copy size={17} /></button><button className="icon-button danger-text" title="Delete template" aria-label={`Delete ${template.name}`} disabled={workspace.templates.length <= 1} onClick={() => { if (window.confirm(`Delete “${template.name}”? Existing invoices will not be affected.`)) onDelete(template.id); }}><Trash2 size={17} /></button></div></div></article>)}<button className="new-template-card" onClick={() => setEditing({ ...defaultTemplate(), name: 'Untitled template' })}><div className="empty-icon"><Plus size={25} /></div><h3>A fresh start</h3><p>Create a template that feels like you.</p></button></div>
  </>;
  return <>
    <div className="page-heading"><div><button className="back-link" onClick={() => { if (window.confirm('Leave the editor? Unsaved template changes will be lost.')) setEditing(null); }}><ArrowLeft size={15} />All templates</button><h1>Template creator</h1><p>A little personality. A professional impression.</p></div><Button variant="primary" onClick={save}><Save size={16} />Save template</Button></div>
    <div className="template-editor-grid"><div className="card template-controls"><Field label="Template name *"><Input value={editing.name} maxLength={100} onChange={e => set('name', e.target.value)} /></Field><div className="segmented"><button className={tab === 'design' ? 'active' : ''} onClick={() => setTab('design')}><SlidersHorizontal size={15} />Design</button><button className={tab === 'content' ? 'active' : ''} onClick={() => setTab('content')}><Type size={15} />Content & fields</button></div>{tab === 'design' ? <>
      <SectionTitle title="Layout & color" /><div className="layout-options">{(['modern', 'classic', 'minimal'] as const).map(layout => <button key={layout} className={editing.layout === layout ? 'active' : ''} onClick={() => set('layout', layout)}><div className={`layout-sketch ${layout}`}><i /><i /><i /></div><span>{layout}</span>{editing.layout === layout && <Check size={12} />}</button>)}</div><Field label="Accent color"><div className="color-input"><input type="color" value={editing.accent} onChange={e => set('accent', e.target.value)} /><span>{editing.accent.toUpperCase()}</span><div className="color-swatches">{['#173f35', '#263e77', '#8a4238', '#5d6171'].map(color => <button key={color} style={{ background: color }} aria-label={`Use color ${color}`} onClick={() => set('accent', color)} />)}</div></div></Field>
      <SectionTitle title="Brand assets" /><Field label="Logo"><Select value={editing.logoAssetId} onChange={e => set('logoAssetId', e.target.value)}><option value="">No logo</option>{workspace.assets.map(asset => <option key={asset.id} value={asset.id}>{asset.name}</option>)}</Select></Field><Field label="Signature image"><Select value={editing.signatureAssetId} onChange={e => set('signatureAssetId', e.target.value)}><option value="">Signature line only</option>{workspace.assets.map(asset => <option key={asset.id} value={asset.id}>{asset.name}</option>)}</Select></Field><p className="small muted asset-hint"><Image size={14} />Upload images in the Asset library first.</p>
      <SectionTitle title="Visible sections" /><Toggle label="HSN / SAC codes" checked={editing.showHSN} onChange={v => set('showHSN', v)} /><Toggle label="Discount column" hint="Discounts still apply when this column is hidden." checked={editing.showDiscount} onChange={v => set('showDiscount', v)} /><Toggle label="Payment details" checked={editing.showBank} onChange={v => set('showBank', v)} /><Toggle label="Authorized signature" checked={editing.showSignature} onChange={v => set('showSignature', v)} /><Field label="Tax presentation" hint="Choose split GST for intra-state sales, single tax for IGST, or a tax-free invoice."><Select value={editing.taxMode} onChange={e => set('taxMode', e.target.value as Template['taxMode'])}><option value="split">Split tax · CGST + SGST</option><option value="single">Single tax · Tax / IGST</option><option value="none">Tax-free</option></Select></Field>
    </> : <>
      <Field label="Document title *"><Input value={editing.title} maxLength={100} onChange={e => set('title', e.target.value)} /></Field><Field label="Terms & conditions"><Textarea rows={5} value={editing.terms} onChange={e => set('terms', e.target.value)} /></Field><Field label="Footer message"><Textarea value={editing.footer} onChange={e => set('footer', e.target.value)} /></Field><SectionTitle title="Custom invoice fields"><span className="count-tag">{editing.customFields.length}/20</span></SectionTitle><p className="small muted">Add details such as registration number, purchase order or rental period. These become input fields on your invoices.</p>{editing.customFields.map((field, index) => <div className="custom-field-card" key={field.id}><div className="line-item-heading"><span>FIELD {index + 1}</span><button className="icon-button danger-text" aria-label={`Remove field ${index + 1}`} onClick={() => set('customFields', editing.customFields.filter(f => f.id !== field.id))}><Trash2 size={14} /></button></div><Field label="Label *"><Input maxLength={100} value={field.label} onChange={e => set('customFields', editing.customFields.map(f => f.id === field.id ? { ...f, label: e.target.value } : f))} /></Field><Field label="Placeholder"><Input value={field.placeholder} onChange={e => set('customFields', editing.customFields.map(f => f.id === field.id ? { ...f, placeholder: e.target.value } : f))} /></Field></div>)}<Button disabled={editing.customFields.length >= 20} onClick={() => set('customFields', [...editing.customFields, { id: uid(), label: 'New field', placeholder: '' }])}><Plus size={15} />Add custom field</Button>
    </>}</div><aside className="preview-panel"><div className="preview-topbar"><span><span className="live-dot" />TEMPLATE PREVIEW</span><span>Sample data</span></div><div className="paper-container"><InvoiceDocument invoice={sample(editing)} sample /></div><p className="preview-caption">The preview uses example customer and item values.</p></aside></div>
  </>;
}
